services:
  mysql:
    container_name: jenkins-hotel-mysql
    ports: !override
      - "3307:3306"

  backend:
    container_name: jenkins-hotel-backend
    ports: !override
      - "5001:5000"

  frontend:
    container_name: jenkins-hotel-frontend
    ports: !override
      - "3001:80"
